// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixgqducbuworkyafzryw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4Z3FkdWNidXdvcmt5YWZ6cnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3Mjk1NzYsImV4cCI6MjA1NDMwNTU3Nn0.tNO7GvNgx1rhlY9RV34Da8Ijz57Q-crN6SENK7mzvQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);